name: Cypress - trabalho_final

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-trabalho-final:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run trabalho_final.spec
        run: |
          npx cypress run --spec "cypress/e2e/trabalho_final.cy.js" \
            --reporter cypress-mochawesome-reporter \
            --browser electron --headless -- \
            --disable-gpu --disable-software-rasterizer

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports
